### ISSUE TITLE
Minor: in board overview/thread there is no space between date and page amount

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber#13]
browser: firefox klar, ios (cellphone)

there is probably just padding or a space char missing between the last digit of "date last answer" and the first digit of "amount pages".
<img width="375" alt="2023-01-17 09-38-04-0" src="https://user-images.githubusercontent.com/6689231/212849263-b8ca9030-123a-459e-8be8-07595e7cf7d9.png">

**Comment by spuxx1701** [comment]
fixed in https://github.com/spuxx1701/potber/commit/e98e6365314b879af943e3a34ebe3aa1cad10d06
