### ISSUE TITLE
request: after page change start scope of page

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber#14]
Current: When changing to another page, the page focus (which post is in focus) stays - so after going one page forward (11 to 12 per example) i have to scroll up because to focus stick to the bottom of the page. While reading backwards, i have the same problem: focus sticks to the top of the page while i want to read bottom up after page switch.

request:
Change post focus in forward page changes to start on top, backwards to start on bottom.

hint:
if i wont switch to the next but a complete different page, the direction would make no sense anymore and scope should be always top.

**Comment by Flitzpiepe42** [comment]
Weird. Hab jetzt auf FF Klar getestet (App vorher geschlossen, das Teil hat ja kein Cache):
Habe die Produktivseite aufgerufen, bin nach pot-news gesurft:

1. Seite öffnet auf letzter Seite (Seite 30) oben
2. scrolle runter, wechsle auf Seite 29 über den Pfeil in der Navbar unten
3. Lande auf Seite 29 oben.
4. Scrolle runter, wechsel auf Seite 30
5. bin auf Seite 30 unten
6. zurück lande ich wieder Seite 29 oben

zwei Mal reproduziert.

Eventuell prüfst du den Fokuswechsel nicht immer?
Soll ich weitere Tests fahren?

**Comment by spuxx1701** [comment]
Die Produktivseite bespiele ich aktuell noch nicht regelmäßig. Geht's denn auf Test bei Dir?

**Comment by Flitzpiepe42** [comment]
kann ich nicht sagen, weil ich als ios-user von dem regexp-blackscreen betroffen bin :/

**Comment by spuxx1701** [comment]
Ich denke das ist fixed, deswegen schließe ich den Issue mal. Falls das auf test.potber.de doch noch auftaucht, gerne wieder aufmachen.
